#!/usr/bin/env bash
# Setup ComfyUI for Qwen Image Edit on macOS Apple Silicon (MPS)
set -e

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
COMFYUI_DIR="$PROJECT_DIR/ComfyUI"
VENV_DIR="$PROJECT_DIR/venv"
DATA_MODELS_DIR="$PROJECT_DIR/data/models"

echo "=== ComfyUI Setup for Qwen Image Edit (MPS / M-series Mac) ==="
echo "Project: $PROJECT_DIR"

# ── 1. Clone ComfyUI ──────────────────────────────────────────────────────────
if [ ! -d "$COMFYUI_DIR" ]; then
    echo ""
    echo "[1/5] Cloning ComfyUI..."
    git clone https://github.com/comfyanonymous/ComfyUI.git "$COMFYUI_DIR"
else
    echo "[1/5] ComfyUI already present, pulling latest..."
    git -C "$COMFYUI_DIR" pull --ff-only
fi

# ── 2. Python venv ────────────────────────────────────────────────────────────
echo ""
echo "[2/5] Setting up Python 3.11 venv..."
if [ ! -d "$VENV_DIR" ]; then
    python3.11 -m venv "$VENV_DIR"
fi
# shellcheck disable=SC1091
source "$VENV_DIR/bin/activate"

pip install --upgrade pip --quiet

echo "    Installing from requirements.txt..."
pip install --quiet -r "$PROJECT_DIR/requirements.txt"

# ComfyUI has its own requirements.txt that fills in any remaining deps
echo "    Installing ComfyUI requirements..."
pip install --quiet -r "$COMFYUI_DIR/requirements.txt"

# ── 3. Custom nodes ───────────────────────────────────────────────────────────
echo ""
echo "[3/5] Installing custom nodes (TextEncodeQwenImageEditPlus)..."
CUSTOM_NODES_DIR="$COMFYUI_DIR/custom_nodes"
mkdir -p "$CUSTOM_NODES_DIR"

# ComfyUI-Manager (optional but useful for finding/managing nodes)
if [ ! -d "$CUSTOM_NODES_DIR/ComfyUI-Manager" ]; then
    git clone --depth 1 https://github.com/ltdrdata/ComfyUI-Manager.git \
        "$CUSTOM_NODES_DIR/ComfyUI-Manager" 2>/dev/null \
        && echo "    ✓ ComfyUI-Manager installed" \
        || echo "    ✗ Could not install ComfyUI-Manager (optional)"
fi

# TextEncodeQwenImageEditPlus — try known repos in order
QWEN_NODE_DIR="$CUSTOM_NODES_DIR/ComfyUI-QwenEdit"
if [ ! -d "$QWEN_NODE_DIR" ]; then
    INSTALLED=false
    TRIED_REPOS=""
    for REPO in \
        "https://github.com/ShmuelRonen/ComfyUI_QwenEdit.git" \
        "https://github.com/Jmkl666/ComfyUI-QwenEdit.git" \
        "https://github.com/spacepxl/ComfyUI-QwenEdit.git"; do
        TRIED_REPOS="$TRIED_REPOS\n      $REPO"
        if git clone --depth 1 "$REPO" "$QWEN_NODE_DIR" 2>/dev/null; then
            echo "    ✓ Installed TextEncodeQwenImageEditPlus from: $REPO"
            INSTALLED=true
            break
        fi
    done
    if [ "$INSTALLED" = false ]; then
        echo ""
        echo "    ⚠  Could not auto-install TextEncodeQwenImageEditPlus."
        echo "    Tried repos:$TRIED_REPOS"
        echo ""
        echo "    Manual install options:"
        echo "      a) Open ComfyUI UI → Manager → Install Custom Nodes → search 'QwenEdit'"
        echo "      b) Or check: https://registry.comfy.org (search TextEncodeQwenImageEditPlus)"
        echo ""
    fi
else
    echo "    ✓ Qwen custom nodes already present"
fi

# Install custom nodes requirements if present
for REQ in "$CUSTOM_NODES_DIR"/*/requirements.txt; do
    [ -f "$REQ" ] && pip install --quiet -r "$REQ"
done

# ── 4. Model path config ──────────────────────────────────────────────────────
echo ""
echo "[4/5] Configuring model paths..."

# Write extra_model_paths.yaml so ComfyUI finds models in data/
cat > "$COMFYUI_DIR/extra_model_paths.yaml" <<YAML
# Auto-generated by setup.sh — points ComfyUI to project data/models/
qwen_v23:
    base_path: ${DATA_MODELS_DIR}/Qwen-Image-Edit-Rapid-AIO/v23/
    checkpoints: .
YAML

echo "    ✓ extra_model_paths.yaml written → models in data/ are now visible to ComfyUI"
echo "    Model name in workflows: Qwen-Rapid-AIO-NSFW-v23.safetensors"

# ── 5. Input / output dirs ────────────────────────────────────────────────────
echo ""
echo "[5/5] Creating working directories..."
mkdir -p "$PROJECT_DIR/input_images"
mkdir -p "$PROJECT_DIR/output_images"
echo "    ✓ input_images/  — drop source images here"
echo "    ✓ output_images/ — generated images will be saved here"

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo "=== Setup Complete ==="
echo ""
echo "Start ComfyUI server:"
echo "  source venv/bin/activate"
echo "  python ComfyUI/main.py --use-pytorch-cross-attention --listen 127.0.0.1 --port 8188"
echo ""
echo "Run batch inference (server must be running):"
echo "  python scripts/run_inference.py \\"
echo "    --input-dir input_images \\"
echo "    --output-dir output_images \\"
echo "    --prompt 'your edit instruction here' \\"
echo "    --nsfw"
echo ""
echo "Or auto-start server + run inference in one command:"
echo "  python scripts/run_inference.py \\"
echo "    --input-dir input_images \\"
echo "    --output-dir output_images \\"
echo "    --prompt 'your edit instruction here' \\"
echo "    --nsfw --auto-start"
